#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
     -v KIAN_ADMIN_PASSWORD="$KIAN_ADMIN_PASSWORD" \
     -v MIGRATION_PASSWORD="$MIGRATION_PASSWORD" \
     -v APP_PASSWORD="$APP_PASSWORD" \
     -U "$POSTGRES_USER" \
     -d "$POSTGRES_DB" <<-EOSQL

ALTER ROLE kian_admin WITH PASSWORD :'KIAN_ADMIN_PASSWORD';
ALTER ROLE migration_user WITH PASSWORD :'MIGRATION_PASSWORD';
ALTER ROLE app_user WITH PASSWORD :'APP_PASSWORD';

EOSQL